name: Run test-runner Script

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 */2 * * *' # Runs every 2 hours

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'

      - name: Install Playwright
        run: npm install playwright && npx playwright install chromium

      - name: Install dependencies
        run: npm install axios  # Install axios module

      - name: Install Xvfb (GUI Emulator)
        run: sudo apt update && sudo apt install -y xvfb

      - name: Clear old Blockman profile
        run: rm -rf /home/runner/Blockman/bloKms33km

      - name: Clear old extKms33km files
        run: rm -rf /home/runner/Blockman/extKms33km

      - name: Extract Blockman Profiles
        run: |
          mkdir -p /home/runner/Blockman/
          for i in {1..6}; do
            tar -xzvf bloKms33km-$i.tar.gz -C /home/runner/Blockman/
          done

      - name: Extract Extensions
        run: |
          mkdir -p /home/runner/Blockmesh/
          for i in {1..6}; do
            tar -xzvf extKms33km_$i.tar.gz -C /home/runner/Blockman/
          done

      - name: Start Xvfb (Simulate GUI)
        run: Xvfb :99 -screen 0 1920x1080x24 &

      - name: Run bloKms33km Scripts
        run: |
          for i in {1..6}; do
            node bloKms33km-$i.js &
          done
        env:
          DISPLAY: ':99.0'  # Use Xvfb display for GUI support
