name: Run Block-tester Scripts

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 */3 * * *' # Runs every 2 hours

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'

      - name: Install Playwright
        run: npm install playwright && npx playwright install chromium

      - name: Install dependencies
        run: npm install axios  # Install axios module

      - name: Install Xvfb (GUI Emulator)
        run: sudo apt update && sudo apt install -y xvfb

      - name: Clear old Blockman profile
        run: rm -rf /home/runner/Blockman/Blockman

      - name: Clear old extension files
        run: rm -rf /home/runner/Blockman/extension

      - name: Extract Blockman & Extension Files One by One
        run: |
          mkdir -p /home/runner/blockman/
          for i in {1..6}; do
            echo "Extracting bloKms33km-$i.tar.gz..."
            tar -xzvf bloKms33km-$i.tar.gz -C /home/runner/blockman/
            
            echo "Extracting extKms33km_$i.tar.gz..."
            tar -xzvf extKms33km_$i.tar.gz -C /home/runner/blockman/

            echo "Extraction completed for set $i"
          done

      - name: Start Xvfb (Simulate GUI)
        run: Xvfb :99 -screen 0 1920x1080x24 &

      - name: Run Blockman Scripts with Logging and Timeout
        run: |
          mkdir -p /home/runner/Blockman/logs  # Create logs directory
          for i in {1..6}; do
            echo "Starting meshk33-$i.js..."
            node meshk33-$i.js > /home/runner/Blockman/logs/meshk33-$i.log 2>&1 &  
            sleep 2  # Give each script time to start before launching the next
          done
          
          echo "All scripts started. Monitoring logs for 5 hours and 2 minutes..."
          sleep $(( 5 * 60 * 60 + 2 * 60 ))  # Sleep for 5 hours and 2 minutes
          
          echo "Timeout reached. Exiting with success."
          exit 0  # Exit with success code
        env:
          DISPLAY: ':99.0'  # Use Xvfb display for GUI support
